import { useLocalSearchParams } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { getAuth } from '@react-native-firebase/auth';
import { doc, getFirestore, onSnapshot } from '@react-native-firebase/firestore';

type Billing = { baseAmount?: number; extraTimeMinutes?: number; extraTimeAmount?: number; totalAmount?: number; };
type Booking = { customerId?: string; maidDetails?: { name?: string }; status?: string; billing?: Billing; paymentStatus?: 'pending' | 'received'; paymentMethod?: 'cash' | 'upi' | null };
function money(value: unknown) { const n=Number(value); return Number.isFinite(n)?`₹${Math.round(n)}`:'—'; }
export default function CustomerBillingRoute() {
 const { bookingId: routeBookingId } = useLocalSearchParams<{ bookingId: string }>();
 const bookingId = String(routeBookingId ?? '');
 const [booking,setBooking]=useState<Booking|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{ const uid=getAuth().currentUser?.uid; if(!uid||!bookingId){setError('Unable to load bill.');setLoading(false);return;} return onSnapshot(doc(getFirestore(),'bookings',bookingId),snap=>{if(!snap.exists()){setError('Booking not found.');setLoading(false);return;} const data=snap.data() as Booking; if(data.customerId!==uid){setError('You do not have access to this bill.');setLoading(false);return;} setBooking(data);setLoading(false);},e=>{console.error('[CustomerBilling] Listener failed:',e);setError(e.message||'Unable to load bill.');setLoading(false);});},[bookingId]);
 if(loading)return <View style={styles.center}><ActivityIndicator size="large" color="#1F7A4C"/><Text style={styles.muted}>Loading bill...</Text></View>;
 if(!booking||!booking.billing)return <View style={styles.center}><Text style={styles.title}>{error||'Bill is not available yet.'}</Text><Pressable style={styles.button} onPress={()=>router.replace('/customer')}><Text style={styles.buttonText}>Back to home</Text></Pressable></View>;
 const b=booking.billing;
 return <ScrollView style={styles.container} contentContainerStyle={styles.content}><View style={styles.header}><Text style={styles.eyebrow}>HOMEHELP</Text><Text style={styles.title}>Payment & Billing</Text><Text style={styles.subtitle}>Your booking has been completed</Text></View><View style={styles.success}><Text style={styles.successTitle}>✓ Booking completed</Text><Text style={styles.successText}>Help: {booking.maidDetails?.name||'—'}</Text></View><View style={styles.card}><Row label="Base amount" value={money(b.baseAmount)}/><Row label="Extra time" value={`${b.extraTimeMinutes??0} min`}/><Row label="Extra time amount" value={money(b.extraTimeAmount)}/><View style={styles.divider}/><Row label="Total amount" value={money(b.totalAmount)} strong/></View><View style={styles.card}><Row label="Payment status" value={booking.paymentStatus==='received'?'Paid':'Pending'}/><Row label="Payment method" value={booking.paymentMethod?booking.paymentMethod.toUpperCase():'—'}/></View><Text style={styles.note}>No online payment gateway is used. This is your final billing summary.</Text><Pressable style={styles.button} onPress={()=>router.replace('/customer')}><Text style={styles.buttonText}>Back to home</Text></Pressable></ScrollView>;
}
function Row({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <View style={styles.row}><Text style={[styles.label,strong&&styles.strong]}>{label}</Text><Text style={[styles.value,strong&&styles.total]}>{value}</Text></View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F7F8F6'},content:{padding:20,paddingBottom:36},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24,backgroundColor:'#F7F8F6'},muted:{marginTop:10,color:'#707770'},header:{marginBottom:18},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#1F7A4C'},title:{marginTop:5,fontSize:27,fontWeight:'900',color:'#121612'},subtitle:{marginTop:4,fontSize:13,color:'#707770'},success:{padding:18,borderRadius:20,backgroundColor:'#EAF5EE',marginBottom:15},successTitle:{fontSize:17,fontWeight:'900',color:'#1F7A4C'},successText:{marginTop:6,fontSize:13,color:'#536057'},card:{backgroundColor:'#FFF',borderRadius:19,borderWidth:1,borderColor:'#E2E7E3',paddingHorizontal:16,marginBottom:15},row:{minHeight:56,flexDirection:'row',alignItems:'center'},label:{flex:1,fontSize:12,color:'#7A817B'},value:{fontSize:14,fontWeight:'800',color:'#202520'},strong:{fontWeight:'900',color:'#202520'},total:{fontSize:20,color:'#1F7A4C'},divider:{height:1,backgroundColor:'#ECEFEC'},note:{fontSize:12,lineHeight:18,color:'#737B75',marginBottom:4},button:{height:50,borderRadius:15,backgroundColor:'#1F7A4C',alignItems:'center',justifyContent:'center',marginTop:14},buttonText:{fontSize:14,fontWeight:'900',color:'#FFF'}});
